import json

def get_translations():
    return{
        "Asset": "Ativos",
        "Category": "Categorias",
        "City": "Cidades",
        "Contract": "Contratos",
        "Contract_Item": "Itens",
        "Contract_Measurement": "Bol. de medição",
        "Contract_Measurement_Record": "Registros de BM.",
        "Contract_Adjustment": "Reajustes",
        "Contract_Item_Highway": "Rodovias",
        "Contract_Item_Order": "Ped. SAP",
        "Contract_Item_Asset": "Ativos",
        "Contract_Item_Work_Role": "Funções",
        "Contract_Item_City": "Cidades",
        "Contract_Measurement_Asset": "Ativos",
        "Contract_Measurement_Work_Role": "Funções",
        "Contract_Measurement_Record_Material": "Materiais",
        "Contract_Measurement_Record_Asset": "Ativos",
        "Contract_Measurement_Record_Work_Role": "Funções",
        "Contract_Adjustment_Data": "Dados do reajuste",
        "Contracted_Company": "Empresa contratada",
        "Highway": "Rodovias",
        "Highway_City": "Cidades",
        "Holiday": "Feriados",
        "Item_Classification": "Classificação de itens",
        "Material": "Materiais",
        "Person": "Pessoa",
        "Contract_Measurement_City": "Cidades",
        "Contract_Measurement_FTD": "Fat. direto",
        "Contract_Measurement_SAP_Order": "Ped. SAP",
        "Work_Role": "Funções",
        "Contract_Measurement_Record_Log": "Relatórios",
        "Contract_Measurement_Record_Resource": "Recursos",
        "Contract_Measurement_Item": "Itens",
        "Contract_Measurement_Record_Time": "Apontamentos de horas",
        "Contract_Item_Type": "Tipos de itens",
        "Item": "Modelos de itens",
        "Unit": "Unidades",
        "Subsidiary": "Concessionárias",
        "SAP_Order_Highway": "Rodovias",
        "SAP_Order_Period": "Linhas",
        "Item Group": "Grupos de itens",
        "Item_Sub_Group": "Subgrupos de itens",

    }