import json

def get_translations():
    return{
        "Asset": "Ativo",
        "Asset_Operator": "Operador",
        "Category": "Categoria",
        "City": "Cidade",
        "Contract": "Contrato",
        "Contract_Item": "Item de Contrato",
        "Contract_Measurement": "Medição de Contrato BM",
        "Contract_Measurement_Record": "Registro de Medição de Contrato",
        "Contract_Adjustment": "Reajuste de Contrato",
        "Contract_Item_Highway": "Rodovia Item de Contrato",
        "Contract_Item_Order": "Pedido SAP Item de Contrato",
        "Contract_Item_Asset": "Ativo Item de Contrato",
        "Contract_Item_Work_Role": "Função Item de Contrato",
        "Contract_Item_City": "Cidade Item de Contrato",
        "Contract_Measurement_Asset": "Ativo BM",
        "Contract_Measurement_Work_Role": "Função BM",
        "Contract_Measurement_Retention": "Retenção de BM",
        "Contract_Measurement_Record_Time": "Tempo de Registro BM",
        "Contract_Measurement_Record_Material": "Material de Registro BM",
        "Contract_Measurement_Record_Asset": "Ativo de Registro BM",
        "Contract_Measurement_Record_Work_Role": "Função no Registro BM",
        "Contract_Adjustment_Data": "Dados de Reajuste de Contrato",
        "Contracted_Company": "Empresa Contratada",
        "Depth_Period_Setting": "Periodo de Medição",
        "Formula": "Fórmula",
        "Formula_Template": "Modelo de Fórmula",
        "Highway": "Rodovia",
        "Highway_City": "Cidade de Rodovia",
        "Holiday": "Feriado",
        "Item_Classification": "Classificação de Item",
        "Item_Classification_Tax": "Classificação de Item ISS",
        "Material": "Material",
        "Person": "Pessoa",
        "Retention_Type": "Tipo de Retenção",
        "Contract_Measurement_City": "Cidade BM",
        "Contract_Measurement_FTD": "FTD de BM",
        "Contract_Measurement_Result": "Resultado de Calculo de BM",
        "Contract_Measurement_SAP_Order": "Pedido SAP de BM",
        "Work_Role": "Função",
        "Contract Measurement Record Rdo": "Medição de Contrato BM Rdo",
        "Contract Measurement Record Rdo Log": "Medição de Contrato BM Rdo Apontamentos",
        "Contract Measurement Record Rdo Item": "Recursos"
    }