import json

def get_translations():
    return{
        "Asset": "Ativo",
        "Asset_Operator": "Operador de Ativo",
        "Category": "Categoria",
        "City": "Cidade",
        "Contract": "Contrato",
        "Contract_Item": "Item de Contrato",
        "Contract_Measurement": "Medição de Contrato",
        "Contract_Measurement_Record": "Registro de Medição de Contrato",
        "Contract_Adjustment": "Ajuste de Contrato",
        "Contract_Item_Highway": "Rodovia de Item de Contrato",
        "Contract_Item_Order": "Pedido de Item de Contrato",
        "Contract_Item_Asset": "Ativo de Item de Contrato",
        "Contract_Item_Work_Role": "Função de Trabalho de Item de Contrato",
        "Contract_Item_City": "Cidade de Item de Contrato",
        "Contract_Measurement_Asset": "Ativo de Medição de Contrato",
        "Contract_Measurement_Work_Role": "Função de Trabalho de Medição de Contrato",
        "Contract_Measurement_Retention": "Retenção de Medição de Contrato",
        "Contract_Measurement_Record_Time": "Tempo de Registro de Medição de Contrato",
        "Contract_Measurement_Record_Material": "Material de Registro de Medição de Contrato",
        "Contract_Measurement_Record_Asset": "Ativo de Registro de Medição de Contrato",
        "Contract_Measurement_Record_Work_Role": "Função de Trabalho de Registro de Medição de Contrato",
        "Contract_Adjustment_Data": "Dados de Ajuste de Contrato",
        "Contract_Test": "Teste de Contrato",
        "Contracted_Company": "Empresa Contratada",
        "Depth_Period_Setting": "Configuração de Período de Profundidade",
        "Formula": "Fórmula",
        "Formula_Template": "Modelo de Fórmula",
        "Highway": "Rodovia",
        "Highway_City": "Cidade de Rodovia",
        "Holiday": "Feriado",
        "Item_Classification": "Classificação de Item",
        "Item_Classification_Tax": "Imposto de Classificação de Item",
        "Material": "Material",
        "Measurement_Report": "Relatório de Medição",
        "Person": "Pessoa",
        "Retention_Type": "Tipo de Retenção",
        "Contract_Measurement_City": "Cidade de Medição de Contrato",
        "Contract_Measurement_FTD": "FTD de Medição de Contrato",
        "Contract_Measurement_Result": "Resultado de Medição de Contrato",
        "Contract_Measurement_SAP_Order": "Pedido SAP de Medição de Contrato",
        "Work_Role": "Função de Trabalho"
    }